FROM python:3.8-buster

COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

COPY . /dallebot
RUN cd /dallebot && python3 -m pip install .

WORKDIR /dallebot
